name: ci-node-aplication
on:
  pull_request:
    branches:
    - develop
jobs:
  run-cijs:
    runs-on: ubuntu:latest
  steps:    
  - name: checkout aplication
    uses: actions/checkout@v2
  - name: setup node 
    uses: actions/setup-node@v2
    with:
      node-version: "16"
  - name: Install the requirements
    run : npm install 
  - name : Run Tests 
    run : npm test 
  - name: SonarCloud Scan
    uses: SonarSource/sonarcloud-github-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

